// <auto-generated />
using System;
using FinanceApp.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117165148_AddReferralSystem")]
    partial class AddReferralSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinanceApp.Shared.Models.Budget", b =>
                {
                    b.Property<int>("id_budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_budget"));

                    b.Property<int>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<int>("nr_alertaPorcentagem")
                        .HasColumnType("int");

                    b.Property<int>("nr_ano")
                        .HasColumnType("int");

                    b.Property<int>("nr_mes")
                        .HasColumnType("int");

                    b.Property<decimal>("nr_valorLimite")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_budget");

                    b.HasIndex("id_categoria");

                    b.ToTable("budgets");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Category", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_categoria"));

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_icone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_categoria");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.CreditCard", b =>
                {
                    b.Property<int>("id_credit_card")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_credit_card"));

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<int?>("id_wallet_pagamento")
                        .HasColumnType("int");

                    b.Property<string>("nm_bandeira")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nr_dia_fechamento")
                        .HasColumnType("int");

                    b.Property<int>("nr_dia_vencimento")
                        .HasColumnType("int");

                    b.Property<decimal>("nr_limite")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_credit_card");

                    b.HasIndex("id_usuario");

                    b.HasIndex("id_wallet_pagamento");

                    b.ToTable("creditCards");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Goal", b =>
                {
                    b.Property<int>("id_goal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_goal"));

                    b.Property<DateTime?>("dt_prazo")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("nr_valorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("nr_valorObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_goal");

                    b.HasIndex("id_usuario");

                    b.ToTable("goals");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Lancamento", b =>
                {
                    b.Property<int>("id_lancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_lancamento"));

                    b.Property<DateTime>("dt_dataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int?>("id_credit_card")
                        .HasColumnType("int");

                    b.Property<int?>("id_goal")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<int?>("id_wallet")
                        .HasColumnType("int");

                    b.Property<string>("nm_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_formaPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nr_parcelaInicial")
                        .HasColumnType("int");

                    b.Property<int>("nr_parcelas")
                        .HasColumnType("int");

                    b.Property<int>("nr_parcelasPagas")
                        .HasColumnType("int");

                    b.Property<decimal>("nr_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_lancamento");

                    b.HasIndex("id_categoria");

                    b.HasIndex("id_credit_card");

                    b.HasIndex("id_goal");

                    b.HasIndex("id_wallet");

                    b.ToTable("lancamentos");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.RecurringTransaction", b =>
                {
                    b.Property<int>("id_transacaoRecorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_transacaoRecorrente"));

                    b.Property<DateTime?>("dt_fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dt_inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dt_ultimaProcessamento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("fl_ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int?>("id_credit_card")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<int?>("id_wallet")
                        .HasColumnType("int");

                    b.Property<string>("nm_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_frequencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("nr_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_transacaoRecorrente");

                    b.HasIndex("id_categoria");

                    b.ToTable("recurringTransactions");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.User", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("cd_referralCode")
                        .HasColumnType("longtext");

                    b.Property<string>("cd_segredo2FA")
                        .HasColumnType("longtext");

                    b.Property<string>("cd_tokenConfirmacao")
                        .HasColumnType("longtext");

                    b.Property<string>("cd_tokenRecuperacao")
                        .HasColumnType("longtext");

                    b.Property<string>("ds_sobre")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("dt_expiracaoToken")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("fl_2faHabilitado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("fl_admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("fl_emailConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("hs_senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("id_referrer")
                        .HasColumnType("int");

                    b.Property<string>("nm_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_funcao")
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nr_indicacoes")
                        .HasColumnType("int");

                    b.Property<string>("nr_telefone")
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_referrer");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Wallet", b =>
                {
                    b.Property<int>("id_wallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_wallet"));

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("nr_saldo_inicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_wallet");

                    b.HasIndex("id_usuario");

                    b.ToTable("wallets");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Budget", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_categoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.CreditCard", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApp.Shared.Models.Wallet", "WalletPagamento")
                        .WithMany()
                        .HasForeignKey("id_wallet_pagamento");

                    b.Navigation("Usuario");

                    b.Navigation("WalletPagamento");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Goal", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Lancamento", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_categoria");

                    b.HasOne("FinanceApp.Shared.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("id_credit_card");

                    b.HasOne("FinanceApp.Shared.Models.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("id_goal");

                    b.HasOne("FinanceApp.Shared.Models.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("id_wallet");

                    b.Navigation("Categoria");

                    b.Navigation("CreditCard");

                    b.Navigation("Goal");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.RecurringTransaction", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.User", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.User", "Referrer")
                        .WithMany()
                        .HasForeignKey("id_referrer");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Wallet", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
