// <auto-generated />
using System;
using FinanceApp.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116064635_AddCategories")]
    partial class AddCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinanceApp.Shared.Models.Category", b =>
                {
                    b.Property<int>("id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_icone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_categoria");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Lancamento", b =>
                {
                    b.Property<int>("id_lancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dt_dataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("id_categoria")
                        .HasColumnType("int");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_formaPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nr_parcelaInicial")
                        .HasColumnType("int");

                    b.Property<int>("nr_parcelas")
                        .HasColumnType("int");

                    b.Property<int>("nr_parcelasPagas")
                        .HasColumnType("int");

                    b.Property<decimal>("nr_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_lancamento");

                    b.HasIndex("id_categoria");

                    b.ToTable("lancamentos");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.User", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("fl_admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("hs_senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FinanceApp.Shared.Models.Lancamento", b =>
                {
                    b.HasOne("FinanceApp.Shared.Models.Category", "Categoria")
                        .WithMany()
                        .HasForeignKey("id_categoria");

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
