// <auto-generated />
using System;
using FinanceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106181517_AddFormaPagamentoParcelas")]
    partial class AddFormaPagamentoParcelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinanceApp.Models.Lancamento", b =>
                {
                    b.Property<int>("id_lancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dt_dataLancamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("nm_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_formaPagamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nr_parcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("nr_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_lancamento");

                    b.ToTable("lancamentos");
                });

            modelBuilder.Entity("FinanceApp.Models.User", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("hs_senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nm_nomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_usuario");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
