// <auto-generated />
using System;
using FinanceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FinanceApp.Models.Lancamento", b =>
                {
                    b.Property<int>("hs_id_lancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("hs_data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("hs_descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("hs_id_user")
                        .HasColumnType("int");

                    b.Property<string>("hs_tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("hs_valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("hs_id_lancamento");

                    b.HasIndex("hs_id_user");

                    b.ToTable("lancamentos");
                });

            modelBuilder.Entity("FinanceApp.Models.User", b =>
                {
                    b.Property<int>("hs_id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("hs_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hs_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hs_password_hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("hs_id_user");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FinanceApp.Models.Lancamento", b =>
                {
                    b.HasOne("FinanceApp.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("hs_id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
